const DOCTOR_COLLECTION_NAME = "Doctor";
const DOCTOR_PATH = "/doctor";
const NOT_FOUND = "NOT_FOUND";
module.exports = {
  DOCTOR_COLLECTION_NAME: DOCTOR_COLLECTION_NAME,
  DOCTOR_PATH: DOCTOR_PATH,
  NOT_FOUND: NOT_FOUND,
};
