const USER_COLLECTION_NAME = "User";
const USER_PATH = "/user";
const NOT_FOUND = "NOT_FOUND";
module.exports = {
  USER_COLLECTION_NAME: USER_COLLECTION_NAME,
  USER_PATH: USER_PATH,
  NOT_FOUND: NOT_FOUND,
};
